### ISSUE TITLE
Project webpage link [http://brew.sh/homebrew-nginx] is broken

### ISSUE THREAD

**Issue by kkshetty** [Homebrew/homebrew-nginx#254]
Hey there.

This is not an issue regarding the codebase, but regarding the link to the project webpage => http://brew.sh/homebrew-nginx.

It appears to be a broken link, and leads to a 404 page.

Is there an alternate link?

**Comment by marcqualie** [comment]
This appears to be affecting all brew.sh formula URLs, looks like the DNS resolves to Rackspace rather than Github Pages now which prevents the project mapping to work as it used to.

@MikeMcQuaid do you know if this is an intended removal or there are new alternative URLs?

I've put a temporary copy on at the following URL: https://homebrew-nginx.marcqualie.com/

**Comment by MikeMcQuaid** [comment]
Sorry, I didn't realise people were relying on the subfolders. This was necessary to get HTTPS support working (unsupported with GitHub Pages today). I'll setup a redirect.

**Comment by MikeMcQuaid** [comment]
> http://brew.sh/homebrew-nginx.

I've added a redirect here. I could setup a new subdomain nginx.brew.sh if that was desirable.

**Comment by kkshetty** [comment]
Thanks @MikeMcQuaid
